### ISSUE TITLE
Fix dependencies definitions

### ISSUE THREAD

**Issue by equinusocio** [eastslopestudio/eleventy-starter#1]
Dependencies in `package.json` are misplaced, most of them are dev dependencies and not public.

```
  "devDependencies": {
    "@11ty/eleventy": "^0.10.0",
    "@babel/core": "^7.8.3",
    "@babel/plugin-proposal-class-properties": "^7.8.3",
    "@babel/preset-env": "^7.8.3",
    "@fullhuman/postcss-purgecss": "^1.3.0",
    "cross-env": "^6.0.3",
    "html-minifier": "^4.0.0",
    "npm-run-all": "^4.1.5",
    "parcel-bundler": "^1.12.4",
    "prettier": "^1.19.1"
  }
```

```
  "dependencies": {
    "stimulus": "^1.1.1",
    "turbolinks": "^5.2.0"
  },
```

PS: rimirar is used as global dependency which may be not installed. I suggest to add is as local `devDep`

**Comment by ryanscherler** [comment]
I'll admit, I am kinda lazy when it comes to npm installing things and just didn't get around to splitting out things. Good catch - I'll update this ;-)
