### ISSUE TITLE
Configuring SCSS

### ISSUE THREAD

**Issue by djmtype** [eastslopestudio/eleventy-starter#10]
For those of us who wouldn't be using Tailwind, but still want to take advantage of PurgeCSS, what's the best way to configure Sass with this? Sass is still useful for some variables that can't be used as custom properties, and source mapping. 

After installing Node Sass, how would we configure it within styles.11ty.js?

**Comment by ryanscherler** [comment]
Hi @djmtype 

I've toyed with moving to straight sass (or creating another version of this starter w/out tailwind and postcss and instead include a barebones sass setup. I haven't just yet as tailwind has been a perfect fit for pretty much every project we start as of late. If I was to look into it, I would see about using the `sass.renderSync()` function somehow in place of the current `await postcss...`

**Comment by ryanscherler** [comment]
I'd prefer to close this issue and move to some sort of 'discussions' feature on this repo. I'll see about setting that up and keep issues to just bugs / new features. Thanks!

**Comment by ryanscherler** [comment]
Looks like a bit of googling and I found a solution https://dev.to/adamkdean/simple-scss-with-11ty-kmn

**Comment by ryanscherler** [comment]
@djmtype Here's what I came up with somewhat quickly (probably requires a bit more real world testing):

```js
const path = require('path')
const sass = require('node-sass-promise')
const postcss = require('postcss')
const cssnano = require('cssnano')

const purgecss = require('@fullhuman/postcss-purgecss')({
  // content relative to /dist
  content: [
    './src/assets/js/**/*.js',
    './src/**/*.njk',
    './src/**/*.md',
    './src/**/*.html',
  ],

  // This is the function used to extract class names from your templates
  defaultExtractor: (content) => {
    // Capture as liberally as possible, including things like `h-(screen-1.5)`
    const broadMatches = content.match(/[^<>"'`\s]*[^<>"'`\s:]/g) || []

    // Capture classes within other delimiters like .block(class="w-1/2") in Pug
    const innerMatches = content.match(/[^<>"'`\s.()]*[^<>"'`\s.():]/g) || []

    return broadMatches.concat(innerMatches)
  },
})

const fileName = 'main.scss'
const permalink = 'assets/main.css'

module.exports = class {
  async data() {
    const rawFilepath = path.join(__dirname, fileName)

    return {
      permalink,
      rawFilepath,
      eleventyExcludeFromCollections: true,
    }
  }

  async render({ rawFilepath }) {
    const { css } = await sass.render({
      file: rawFilepath,
      includePaths: [path.resolve(path.join(__dirname, 'node_modules'))],
    })

    return await postcss([
      require('autoprefixer'),
      ...(process.env.ELEVENTY_ENV === 'production' ? [purgecss, cssnano] : []),
    ])
      .process(css.toString(), { from: permalink })
      .then((result) => result.css)
  }
}

```

**Comment by djmtype** [comment]
Wow, thanks very much @ryanscherler. It's working without css source map. I thought just by looking at the docs and Adam Dean's example, I could figure that out. However, not the case. There's no error, so I'm either very wrong to assume the `outFile` path property, or something else. 

```
const outputFile = path.join(__dirname, permalink)
const { css } = await sass.render({
  file: rawFilepath,
  outFile: outputFile,
  sourceMap: true,
  includePaths: [path.resolve(path.join(__dirname, 'node_modules'))],
})
```

**Comment by ryanscherler** [comment]
@djmtype Sourcemaps are not automatically written to the filesystem (See: https://github.com/sass/node-sass#outfile). You would need to write this yourself OR you can embed the source map into the CSS via something like:

```js
const { css } = await sass.render({
      file: rawFilepath,
      includePaths: ['node_modules'],
      sourceMapContents: true,
      sourceMapEmbed: true,
      sourceMapRoot: fileName,
})
```

**Comment by djmtype** [comment]
@ryanscherler thanks. That's exactly what I ended up doing.
