### ISSUE TITLE
Suggestion: Include a link to a demo showing this template

### ISSUE THREAD

**Issue by anishkny** [eastslopestudio/eleventy-starter#14]
@grantholle @ryanscherler probably in the "About" section of the repo?

**Comment by ryanscherler** [comment]
@anishkny - good reminder! It’s actually been something I have been meaning to do for a while now. Will throw a netlify link up and update the readme

**Comment by ryanscherler** [comment]
Added! https://ess-eleventy-starter.netlify.app/
