### ISSUE TITLE
[Suggestion] Updating PostCSS config

### ISSUE THREAD

**Issue by equinusocio** [eastslopestudio/eleventy-starter#3]
I would suggest to update the postcss config by removing `autoprefixer` and `postcss-nest` and adding [`postcs-preset-env`](https://preset-env.cssdb.org) which include autoprefixer, spec-like nesting and browsers list support. It's like babel-env for postcss

**Comment by ryanscherler** [comment]
I like the idea of postcss-preset-env as it does have a lot of nice features. Though the reason I went the postcss-nested route is that is is more sass-like in its nesting behavior. I often will use a BEM style syntax for creating one off components and like to be able to use this style of CSS:

```css
.block {
  &__element {
     &--modifier {
       
     }
  }
}
```

The CSS spec doesn't allow for concatenation, only specificity rules.

**Comment by equinusocio** [comment]
Make sense, but autoprefixer is included in PostCSS. No need to declare the plugin

**Comment by ryanscherler** [comment]
Good to know autoprefixer is included in postcss! I’ll remove it when I’m back in the office ;-)

>
