### ISSUE TITLE
Add script to clean build before start and build

### ISSUE THREAD

**Issue by equinusocio** [eastslopestudio/eleventy-starter#4]
Right now the `dist` folder is not cleaned before build and watch scripts. The `clean` scripts are not called automatically before such scripts and `rimraf` is not declared as local dev dependency.

**Comment by ryanscherler** [comment]
I normally just run this when needed (the `dist` folder is gitignored anyways), and those folders get re-written to on each subsequent command. But I can go ahead and add that into each script if you think its needed.

**Comment by equinusocio** [comment]
I added it to the watch command by using run-s

`run-s clean:* && run-p watch:* `
