### ISSUE TITLE
Missing 404.md causes Browsersync error

### ISSUE THREAD

**Issue by czechue** [eastslopestudio/eleventy-starter#5]
Hi, 
thank you for creating this starter pack. I really like it :)
One thing it would be nice to add is simple 404.md in site folder, so we won't have this ugly error.

![image](https://user-images.githubusercontent.com/21274642/77222298-49ed4c00-6b52-11ea-8687-c81a3ba0246f.png)

**Comment by ryanscherler** [comment]
Glad it’s working good for you. I agree that a 404 would be a solid addition - want to do a pull request for this?

**Comment by czechue** [comment]
yes no problem :) I will send PR soon
